- id: '1606617514086'
  name: Living Room Bright
  entities:
    light.left_ent_center:
      brightness: 255
      friendly_name: Left Ent Center
      supported_features: 41
      state: 'on'
    light.right_ent_center:
      brightness: 255
      friendly_name: Right Ent Center
      supported_features: 41
      state: 'on'
    light.light_strip:
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - colorloop
      - random
      brightness: 255
      color_temp: 316
      effect: none
      friendly_name: Light Strip
      supported_features: 63
      state: 'on'
  icon: mdi:brightness-5
- id: '1606617991393'
  name: Living Room Medium
  entities:
    light.left_ent_center:
      brightness: 166
      friendly_name: Left Ent Center
      supported_features: 41
      state: 'on'
    light.right_ent_center:
      brightness: 161
      friendly_name: Right Ent Center
      supported_features: 41
      state: 'on'
    light.light_strip:
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - colorloop
      - random
      brightness: 171
      hs_color:
      - 38.095
      - 49.412
      rgb_color:
      - 255
      - 208
      - 128
      xy_color:
      - 0.45
      - 0.404
      effect: none
      friendly_name: Light Strip
      supported_features: 63
      state: 'on'
  icon: mdi:brightness-6
- id: '1606618092546'
  name: Living Room Movie
  entities:
    light.light_strip:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - 'off'
      - candle
      - fire
      - prism
      - sparkle
      - opal
      - glisten
      supported_color_modes:
      - color_temp
      - xy
      effect: 'off'
      color_mode: color_temp
      brightness: 41
      color_temp_kelvin: 3521
      color_temp: 284
      hs_color:
      - 27.152
      - 44.32
      rgb_color:
      - 255
      - 193
      - 142
      xy_color:
      - 0.452
      - 0.373
      mode: normal
      dynamics: none
      friendly_name: Light Strip
      supported_features: 44
      state: 'on'
    light.right_ent_center:
      effect_list:
      - 'off'
      - candle
      supported_color_modes:
      - brightness
      effect: 'off'
      color_mode: brightness
      brightness: 13
      mode: normal
      dynamics: none
      friendly_name: Right Ent Center
      supported_features: 44
      state: 'on'
    light.left_ent_center:
      effect_list:
      - 'off'
      - candle
      supported_color_modes:
      - brightness
      effect: 'off'
      color_mode: brightness
      brightness: 33
      mode: normal
      dynamics: none
      friendly_name: Left Ent Center
      supported_features: 44
      state: 'on'
    light.hue_color_downlight_1:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - 'off'
      - candle
      - fire
      - prism
      - sparkle
      - opal
      - glisten
      - underwater
      - cosmos
      - sunbeam
      - enchant
      - sunrise
      - sunset
      supported_color_modes:
      - color_temp
      - xy
      effect:
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      mode: normal
      dynamics: none
      friendly_name: Hue color downlight 1
      supported_features: 44
      state: 'off'
    light.hue_color_downlight_2:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - 'off'
      - candle
      - fire
      - prism
      - sparkle
      - opal
      - glisten
      - underwater
      - cosmos
      - sunbeam
      - enchant
      - sunrise
      - sunset
      supported_color_modes:
      - color_temp
      - xy
      effect:
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      mode: normal
      dynamics: none
      friendly_name: Hue color downlight 2
      supported_features: 44
      state: 'off'
    light.hue_color_downlight_3:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - 'off'
      - candle
      - fire
      - prism
      - sparkle
      - opal
      - glisten
      - underwater
      - cosmos
      - sunbeam
      - enchant
      - sunrise
      - sunset
      supported_color_modes:
      - color_temp
      - xy
      effect:
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      mode: normal
      dynamics: none
      friendly_name: Hue color downlight 3
      supported_features: 44
      state: 'off'
    light.hue_color_downlight_4:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - 'off'
      - candle
      - fire
      - prism
      - sparkle
      - opal
      - glisten
      - underwater
      - cosmos
      - sunbeam
      - enchant
      - sunrise
      - sunset
      supported_color_modes:
      - color_temp
      - xy
      effect:
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      mode: normal
      dynamics: none
      friendly_name: Hue color downlight 4
      supported_features: 44
      state: 'off'
  icon: mdi:movie-roll
  metadata: {}
- id: '1607246268954'
  name: Night Bedstand
  entities:
    light.jng_nightstand:
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      color_mode: xy
      brightness: 1
      hs_color:
      - 33.767
      - 84.314
      rgb_color:
      - 255
      - 161
      - 40
      xy_color:
      - 0.561
      - 0.4042
      mode: normal
      dynamics: none
      friendly_name: JNG Nightstand
      supported_features: 40
      state: 'on'
    light.hue_color_lamp_1:
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      color_mode: xy
      brightness: 1
      hs_color:
      - 33.767
      - 84.314
      rgb_color:
      - 255
      - 161
      - 40
      xy_color:
      - 0.561
      - 0.4042
      mode: normal
      dynamics: none
      friendly_name: JLR Nightstand
      supported_features: 40
      state: 'on'
  icon: mdi:moon-waning-crescent
  metadata: {}
- id: '1607246470071'
  name: Relax
  entities:
    light.jng_nightstand:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - None
      - candle
      - fire
      - prism
      - sparkle
      - opal
      - glisten
      supported_color_modes:
      - color_temp
      - xy
      effect: None
      color_mode: color_temp
      brightness: 145
      color_temp_kelvin: 2217
      color_temp: 451
      hs_color:
      - 29.737
      - 83.879
      rgb_color:
      - 255
      - 147
      - 41
      xy_color:
      - 0.577
      - 0.388
      mode: normal
      dynamics: none
      friendly_name: JNG Nightstand
      supported_features: 44
      state: 'on'
    light.jlr_nightstand:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - None
      - candle
      - fire
      - prism
      - sparkle
      - opal
      - glisten
      supported_color_modes:
      - color_temp
      - xy
      effect: None
      color_mode: color_temp
      brightness: 145
      color_temp_kelvin: 2000
      color_temp: 500
      hs_color:
      - 30.601
      - 94.547
      rgb_color:
      - 255
      - 136
      - 13
      xy_color:
      - 0.599
      - 0.382
      mode: normal
      dynamics: none
      friendly_name: JLR Nightstand
      supported_features: 44
      state: 'on'
  icon: mdi:sofa
  metadata: {}
- id: '1607246522727'
  name: Bright
  entities:
    light.jng_nightstand:
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      color_mode: color_temp
      brightness: 255
      hs_color:
      - 28.327
      - 64.71
      rgb_color:
      - 255
      - 167
      - 89
      xy_color:
      - 0.524
      - 0.387
      mode: normal
      dynamics: none
      friendly_name: JNG Nightstand
      supported_features: 40
      color_temp: 366
      state: 'on'
    light.hue_color_lamp_1:
      min_mireds: 153
      max_mireds: 500
      supported_color_modes:
      - color_temp
      - xy
      color_mode: color_temp
      brightness: 145
      color_temp: 371
      hs_color:
      - 28.406
      - 65.883
      rgb_color:
      - 255
      - 166
      - 86
      xy_color:
      - 0.527
      - 0.388
      mode: normal
      dynamics: none
      friendly_name: JLR Nightstand
      supported_features: 40
      state: 'on'
  icon: mdi:lightbulb
  metadata: {}
- id: '1620710923891'
  name: Living Room Off
  entities:
    light.left_ent_center:
      effect_list:
      - 'off'
      - candle
      supported_color_modes:
      - brightness
      effect:
      color_mode:
      brightness:
      mode: normal
      dynamics: none
      friendly_name: Left Ent Center
      supported_features: 44
      state: 'off'
    light.right_ent_center:
      effect_list:
      - 'off'
      - candle
      supported_color_modes:
      - brightness
      effect:
      color_mode:
      brightness:
      mode: normal
      dynamics: none
      friendly_name: Right Ent Center
      supported_features: 44
      state: 'off'
    light.light_strip:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - 'off'
      - candle
      - fire
      - prism
      - sparkle
      - opal
      - glisten
      supported_color_modes:
      - color_temp
      - xy
      effect:
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      mode: normal
      dynamics: none
      friendly_name: Light Strip
      supported_features: 44
      state: 'off'
    light.hue_color_downlight_1:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - 'off'
      - candle
      - fire
      - prism
      - sparkle
      - opal
      - glisten
      - underwater
      - cosmos
      - sunbeam
      - enchant
      - sunrise
      - sunset
      supported_color_modes:
      - color_temp
      - xy
      effect:
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      mode: normal
      dynamics: none
      friendly_name: Hue color downlight 1
      supported_features: 44
      state: 'off'
    light.hue_color_downlight_2:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - 'off'
      - candle
      - fire
      - prism
      - sparkle
      - opal
      - glisten
      - underwater
      - cosmos
      - sunbeam
      - enchant
      - sunrise
      - sunset
      supported_color_modes:
      - color_temp
      - xy
      effect:
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      mode: normal
      dynamics: none
      friendly_name: Hue color downlight 2
      supported_features: 44
      state: 'off'
    light.hue_color_downlight_3:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - 'off'
      - candle
      - fire
      - prism
      - sparkle
      - opal
      - glisten
      - underwater
      - cosmos
      - sunbeam
      - enchant
      - sunrise
      - sunset
      supported_color_modes:
      - color_temp
      - xy
      effect:
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      mode: normal
      dynamics: none
      friendly_name: Hue color downlight 3
      supported_features: 44
      state: 'off'
    light.hue_color_downlight_4:
      min_color_temp_kelvin: 2000
      max_color_temp_kelvin: 6535
      min_mireds: 153
      max_mireds: 500
      effect_list:
      - 'off'
      - candle
      - fire
      - prism
      - sparkle
      - opal
      - glisten
      - underwater
      - cosmos
      - sunbeam
      - enchant
      - sunrise
      - sunset
      supported_color_modes:
      - color_temp
      - xy
      effect:
      color_mode:
      brightness:
      color_temp_kelvin:
      color_temp:
      hs_color:
      rgb_color:
      xy_color:
      mode: normal
      dynamics: none
      friendly_name: Hue color downlight 4
      supported_features: 44
      state: 'off'
  icon: mdi:home-lightbulb-outline
  metadata: {}
- id: '1737278663785'
  name: MBR Off
  entities: {}
  icon: mdi:alarm-light-off
  metadata: {}
